Poolmgr concurrency field
fission/docs.fission.io pull request #215
Opened 2020-09-16 08:13 UTC by therahulbhati

2020-09-17 16:01 UTC, vishal-biyani requested changes

2020-09-17 16:01 UTC, vishal-biyani commented on docs/content/en/docs/concepts/components/core/executor.md
> +one pod per function, which is not suitable for serving massive traffic. To overcome
```suggestion
one pod per function, which is not suitable if you want to serve more requests in parallel. To overcome 
```

2020-09-17 16:01 UTC, vishal-biyani commented on docs/content/en/docs/usage/executor.en.md
> +maximum number of concurrent pod specialization(default 5) to serve requests. As of now, `concurrency` field is only supported by poolmgr.
```suggestion
maximum number of concurrent pod specialization(default 5) to serve requests. The `concurrency` field is only supported by poolmgr.
```

2020-09-23 04:16 UTC, vishal-biyani commented
@therahulbhati Resolve Conflicts please.

2020-10-22 17:19 UTC, pyrkamarcin approved these changes

2021-09-23 13:14 UTC, sanketsudake commented
Changes ported to PR https://github.com/fission/docs.fission.io/pull/296

2021-09-23 13:14 UTC, closed without merging