OpenTelemetry usage document
fission/docs.fission.io pull request #282
Opened 2021-08-16 06:13 UTC by gauravgahlot

2021-08-17 09:35 UTC, sanketsudake requested changes

2021-08-17 09:35 UTC, sanketsudake commented on docs/content/en/docs/usage/observability/opentelemetry.md
> +git clone https://github.com/open-telemetry/opentelemetry-go.git
The process seems a bit hectic of cloning repos etc. also not consistent across version of opentelemetry.

https://github.com/open-telemetry/opentelemetry-operator
Should we use an opentelemetry operator instead?

We can include it Fission helm chart as well going  ahead once it stabilizess.

2021-08-17 09:35 UTC, sanketsudake commented on docs/content/en/docs/usage/observability/opentelemetry.md
> +helm install --version 1.14.1 --namespace $FISSION_NAMESPACE \
No need to pin specific versions.
We use this variable `{{% release-version %}}` on the installation page, we can use the same here. 

We can just showcase additional values to set for open telemetry here and point to the installation page.

2021-08-17 09:35 UTC, sanketsudake commented on docs/content/en/docs/usage/observability/opentelemetry.md
> +Currently, Fission supports both - OpenTracing (added a while ago) and OpenTelemetry (new addition).
Let's specific Fission versions here.

2021-08-17 09:35 UTC, sanketsudake commented on docs/content/en/docs/usage/observability/opentelemetry.md
> +### NextJS App
We can use the sample nodejs(hello) function here so that users do not need to lot of setup to get example working.

2021-08-18 11:32 UTC, sanketsudake approved these changes

2021-08-18 11:32 UTC, sanketsudake commented on docs/content/en/docs/usage/observability/opentelemetry.md
> +Up to `1.14.1` release, Fission supports outputting traces to an OpenTracing Jaeger-formatted trace collection endpoint. This is great as it provides lots of insight into what Fission is doing and he
`as we add support for OpenTelemetry`

2021-08-18 11:33 UTC, sanketsudake commented
We will be holding this PR until we release 1.15.

2021-08-29 08:17 UTC, gauravgahlot commented
No changes, only signed the commits.

2021-09-24 07:46 UTC, vishal-biyani commented
LGTM!

2021-09-24 07:46 UTC, vishal-biyani approved these changes

2021-09-24 09:41 UTC, merged